### PR TITLE
Weekend summary

### PR DESCRIPTION
**Pull request by jaimerson**
image

### CODE REVIEW

**Comment by meirabruno** [comment]
:shipit: Je ne sepa suas nega

**Comment by phillipp-oliveira** [comment]
:+1: Je sui suas negas

**Comment by mpivaa** [comment]
:shipit:

**Comment by yoshioteruia** [comment]
Está pronto esse PR?!?

**Comment by jaimerson** [comment]
Tá wip, peraí

**Comment by jaimerson** [comment]
:shipit:

**Pull request merged**
